---
# tasks file for while_true_do.sys_kdump

- name: Gather crashkernel Size
  command: cat /sys/kernel/kexec_crash_size
  changed_when: false
  register: wtd_sys_kdump_crashkernel_size
  become: true
  tags:
    - kdump
    - system

- debug:
    msg: "Cannot install kdump, please configure grub with crashkernel option."
  when:
    - wtd_sys_kdump_crashkernel_size.stdout|int == 0
  tags:
    - kdump
    - system

- name: Manage kdump Packages
  package:
    name: "{{ wtd_sys_kdump_package }}"
    state: "{{ wtd_sys_kdump_package_state }}"
  become: true
  when:
    - wtd_sys_kdump_crashkernel_size.stdout|int > 0
  tags:
    - kdump
    - package
    - system

- name: Configure kdump.conf
  template:
    src: kdump.conf.j2
    dest: /etc/kdump.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Reboot System
  when:
    - wtd_sys_kdump_crashkernel_size.stdout|int > 0
    - wtd_sys_kdump_package_state != "absent"
  tags:
    - kdump
    - configuration
    - system

- name: Manage kdump Service
  service:
    name: "{{ wtd_sys_kdump_service }}"
    state: "{{ wtd_sys_kdump_service_state }}"
    enabled: "{{ wtd_sys_kdump_service_enabled }}"
  become: true
  when:
    - wtd_sys_kdump_crashkernel_size.stdout|int > 0
    - wtd_sys_kdump_package_state != "absent"
  tags:
    - kdump
    - service
    - configuration
